# Generated by Django 4.1.5 on 2023-02-25 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Templates', '0003_alter_detail_temp_cat_alter_detail_temp_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('Portfolio_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Template_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Templates.detail')),
                ('User_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
