# Generated by Django 4.1.5 on 2023-02-25 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='Template_id',
            new_name='Template',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='User_id',
            new_name='User',
        ),
    ]
