# Generated by Django 4.1.5 on 2023-02-25 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Templates', '0003_alter_detail_temp_cat_alter_detail_temp_type'),
        ('Services', '0002_rename_template_id_portfolio_template_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('Resume_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Template', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Templates.detail')),
                ('User', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
