# Generated by Django 4.1.5 on 2023-02-25 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0003_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_info',
            fields=[
                ('Personal_id', models.IntegerField(primary_key=True, serialize=False)),
                ('First_name', models.CharField(max_length=30)),
                ('Last_name', models.CharField(max_length=30)),
                ('Address', models.TextField()),
                ('Phone', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('Dob', models.DateField()),
                ('Philosophy', models.TextField()),
                ('Portfolio', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Services.portfolio')),
                ('Resume', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Services.resume')),
            ],
        ),
    ]
