# Generated by Django 4.1.5 on 2023-02-26 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0004_personal_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('Education_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Institute', models.CharField(max_length=50)),
                ('Degree', models.CharField(max_length=50)),
                ('Start_year', models.CharField(max_length=10)),
                ('End_year', models.CharField(max_length=10)),
                ('Portfolio', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Services.portfolio')),
                ('Resume', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Services.resume')),
            ],
        ),
    ]
