# Generated by Django 4.1.5 on 2023-02-26 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0005_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='Current',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='education',
            name='End_year',
            field=models.CharField(default='no', max_length=10),
        ),
    ]
