# Generated by Django 4.1.5 on 2023-02-26 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0006_education_current_alter_education_end_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('Experience_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Company', models.CharField(max_length=50)),
                ('Role', models.CharField(max_length=30)),
                ('Start_year', models.CharField(max_length=10)),
                ('End_year', models.CharField(default='no', max_length=10)),
                ('Current', models.BooleanField(default=False)),
                ('Portfolio', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Services.portfolio')),
                ('Resume', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Services.resume')),
            ],
        ),
    ]
