# Generated by Django 4.1.5 on 2023-02-26 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0007_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('Project_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=50)),
                ('Start_year', models.CharField(max_length=10)),
                ('End_year', models.CharField(default='no', max_length=10)),
                ('Current', models.BooleanField(default=False)),
                ('Description', models.TextField(default='NO')),
                ('Portfolio', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Services.portfolio')),
                ('Resume', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Services.resume')),
            ],
        ),
    ]
