# Generated by Django 4.1.5 on 2023-02-26 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0008_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('Skill_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Level', models.CharField(max_length=20)),
                ('Portfolio', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Services.portfolio')),
                ('Resume', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Services.resume')),
            ],
        ),
    ]
