# Generated by Django 4.1.5 on 2023-02-26 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0009_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('Award_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=50)),
                ('Institute', models.CharField(max_length=50)),
                ('Year', models.CharField(max_length=10)),
                ('Descriotion', models.TextField(default='NO')),
                ('Portfolio', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Services.portfolio')),
            ],
        ),
    ]
