# Generated by Django 4.1.5 on 2023-02-26 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0010_award'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social_Media',
            fields=[
                ('Social_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Url', models.TextField()),
                ('Portfolio', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Services.portfolio')),
            ],
        ),
    ]
