# Generated by Django 4.1.5 on 2023-03-20 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0011_social_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info',
            name='Portfolio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Services.portfolio'),
        ),
    ]
