# Generated by Django 4.1.5 on 2023-03-20 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0012_alter_personal_info_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info',
            name='Resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Services.resume'),
        ),
    ]
