# Generated by Django 4.1.5 on 2023-03-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0014_alter_education_portfolio_alter_education_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='Description',
            field=models.TextField(default='NO'),
        ),
    ]
