# Generated by Django 4.1.5 on 2023-03-21 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0015_experience_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='Portfolio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Services.portfolio'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='Resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Services.resume'),
        ),
    ]
