# Generated by Django 4.1.5 on 2023-03-25 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0018_alter_award_descriotion_alter_experience_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Portfolio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Services.portfolio'),
        ),
        migrations.AlterField(
            model_name='project',
            name='Resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Services.resume'),
        ),
    ]
