# Generated by Django 4.1.5 on 2023-03-25 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0019_alter_project_portfolio_alter_project_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='Portfolio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Services.portfolio'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='Resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Services.resume'),
        ),
    ]
