# Generated by Django 4.1.5 on 2023-03-25 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0020_alter_skill_portfolio_alter_skill_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='award',
            old_name='Descriotion',
            new_name='Description',
        ),
    ]
