# Generated by Django 4.1.5 on 2023-03-28 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Services', '0021_rename_descriotion_award_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal_info',
            name='Portfolio',
        ),
        migrations.RemoveField(
            model_name='personal_info',
            name='Resume',
        ),
        migrations.AddField(
            model_name='personal_info',
            name='Pic',
            field=models.ImageField(default='default.jpg', upload_to='Personal_Pic'),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='User',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
