# Generated by Django 4.1.5 on 2023-04-23 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0024_alter_personal_info_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_info',
            name='Country',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='Portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Services.portfolio'),
        ),
        migrations.AlterField(
            model_name='education',
            name='Resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Services.resume'),
        ),
    ]
