# Generated by Django 4.1.5 on 2023-04-23 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0027_remove_personal_info_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
