# Generated by Django 4.1.5 on 2023-03-29 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Templates", "0003_alter_detail_temp_cat_alter_detail_temp_type"),
        ("Services", "0023_alter_personal_info_pic"),
    ]

    operations = [
        migrations.CreateModel(
            name="payment",
            fields=[
                ("payment_id", models.IntegerField(primary_key=True, serialize=False)),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "razor_pay_order_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "Portfolio",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Services.portfolio",
                    ),
                ),
                (
                    "Resume",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Services.resume",
                    ),
                ),
                (
                    "Temp_price",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Templates.detail",
                    ),
                ),
            ],
        ),
    ]
