# Generated by Django 4.1.5 on 2023-03-29 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="payment",),
    ]
