# Generated by Django 4.1.5 on 2023-03-31 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='Temp_price',
        ),
        migrations.AddField(
            model_name='payment',
            name='Total',
            field=models.IntegerField(default=0),
        ),
    ]
