# Generated by Django 4.1.5 on 2023-04-01 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_remove_payment_temp_price_payment_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='Order_id',
            field=models.IntegerField(default=0),
        ),
    ]
