# Generated by Django 4.1.5 on 2023-04-01 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_payment_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='Order_id',
        ),
    ]
