# Generated by Django 4.1.5 on 2023-02-19 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('Offer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Offer', models.BooleanField(default=False)),
                ('Offer_value', models.IntegerField()),
                ('Start_date', models.DateField()),
                ('End_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Temp_name', models.CharField(max_length=100)),
                ('Temp_cat', models.CharField(choices=[('P', 'Portfolio'), ('R', 'Resume'), ('A', 'ATS')], default='Portfolio', max_length=30)),
                ('Temp_type', models.CharField(choices=[('B', 'Basic'), ('P', 'Premium')], default='Basic', max_length=30)),
                ('Temp_date', models.DateField()),
                ('Temp_img1', models.ImageField(upload_to='Temp_Imgs')),
                ('Temp_img2', models.ImageField(null=True, upload_to='Temp_Imgs')),
                ('Temp_img3', models.ImageField(null=True, upload_to='Temp_Imgs')),
                ('Temp_des', models.TextField()),
                ('Temp_price', models.IntegerField()),
                ('Temp_file', models.FileField(upload_to='Template')),
                ('Temp_active', models.BooleanField(default=False)),
                ('Temp_offer', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='Templates.offer')),
            ],
        ),
    ]
