# Generated by Django 4.1.5 on 2023-02-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Templates', '0002_alter_detail_temp_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='Temp_cat',
            field=models.CharField(choices=[('Portfolio', 'Portfolio'), ('Resume', 'Resume'), ('ATS', 'ATS')], default='Portfolio', max_length=30),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Temp_type',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Premium', 'Premium')], default='Basic', max_length=30),
        ),
    ]
