# Generated by Django 4.1.5 on 2023-03-05 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Templates", "0003_alter_detail_temp_cat_alter_detail_temp_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Index", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Rate", models.IntegerField(max_length=5)),
                ("Message", models.TextField(max_length=200)),
                ("Date", models.DateField(auto_now_add=True)),
                (
                    "Template",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Templates.detail",
                    ),
                ),
                (
                    "User",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
