# Generated by Django 4.1.5 on 2023-03-05 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Index", "0003_remove_feedback_template_remove_feedback_user_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedback", old_name="Message", new_name="Message1",
        ),
    ]
