# Generated by Django 4.1.5 on 2023-03-18 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Index", "0006_remove_feedback_template"),
    ]

    operations = [
        migrations.RemoveField(model_name="feedback", name="User",),
    ]
