# Generated by Django 4.1.5 on 2023-03-27 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Templates', '0003_alter_detail_temp_cat_alter_detail_temp_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Index', '0007_remove_feedback_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='Template',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Templates.detail'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='User',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
